# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('runtime', models.IntegerField(default=0)),
                ('director_first_name', models.CharField(max_length=30)),
                ('director_last_name', models.CharField(max_length=30)),
                ('genre', models.CharField(blank=True, choices=[('A', 'Action'), ('C', 'Comedy'), ('Dr', 'Drama'), ('F', 'Fantasy'), ('H', 'Horror'), ('S', 'Sci-Fi'), ('Do', 'Documentary')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Owned',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movies.Movie')),
                ('purchase_date', models.DateField(verbose_name='Purchased on')),
                ('rating', models.CharField(blank=True, choices=[(5, 'Great'), (4, 'Good'), (3, 'Okay'), (2, 'Bad'), (1, 'Awful')], max_length=1)),
            ],
            bases=('movies.movie',),
        ),
    ]
