# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20170112_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director_first_name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director_last_name',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, default='Director', max_length=50),
        ),
    ]
