# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_remove_movie_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.ImageField(blank=True, upload_to='cover/'),
        ),
    ]
