# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cover',
        ),
    ]
