# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 21:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_remove_movie_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(message='Illegal characters. Use numbers only', regex='[0-9]')]),
        ),
    ]
