# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20170117_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('scifi', 'Sci-Fi'), ('doc', 'Documentary')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('owned', 'Owned'), ('wishlist', 'Wishlist')], default='owned', max_length=10),
        ),
    ]
