# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20170117_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, choices=[('act', 'Action'), ('com', 'Comedy'), ('dra', 'Drama'), ('fan', 'Fantasy'), ('hor', 'Horror'), ('sci', 'Science Fiction'), ('doc', 'Documentary'), ('rom', 'Romance')], max_length=3),
        ),
    ]
