# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 17:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20170117_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Illegal characters. Use letters only', regex='[A-Za-z]')])),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Director'),
        ),
    ]
