# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 19:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_auto_20170120_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Illegal characters. Use letters only', regex='[A-Za-z ]+$')]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(message='Illegal characters. Use numbers only', regex='[0-9]{4}')]),
        ),
    ]
