# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 20:24
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_auto_20170121_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=stdimage.models.StdImageField(blank=True, upload_to=stdimage.utils.UploadToAutoSlug('title')),
        ),
    ]
