# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 03:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_auto_20170121_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 23, 3, 3, 11, 953850, tzinfo=utc)),
        ),
    ]
