# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_auto_20170122_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
