# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_auto_20170122_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date_added',
        ),
    ]
